baseURL = 'https://echorohit.github.io/'
languageCode = 'en-us'
title = 'Rohit Kumar Choudhary'
theme = 'PaperMod'

[params]
  homeInfoParams.Title = "Hi there 👋"
  homeInfoParams.Content = "Welcome to my digital resume and portfolio"
  
  profileMode.enabled = true
  profileMode.title = "Rohit Kumar Choudhary"
  profileMode.subtitle = "Software Engineer | Backend Architecture | PHP Developer"
  profileMode.imageUrl = "https://github.com/echorohit.png"
  profileMode.imageTitle = "Rohit Kumar Choudhary"
  
  socialIcons = [
    {name = "github", url = "https://github.com/echorohit"},
    {name = "twitter", url = "https://twitter.com/Twittsrohit"},
    {name = "facebook", url = "https://facebook.com/rohitatfacebuk"},
    {name = "email", url = "mailto:mrohitchoudhary@gmail.com"}
  ]
  
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 20
  [[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 30
  [[menu.main]]
    name = "Skills"
    url = "/skills/"
    weight = 40
